#구글 팀 드라이브 application-oauth.yml문서 복사 붙여넣기

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${K_CLIIENT_ID}
            client-secret: ${K_CLIIENT_SECRET}
            client-name: kakao
            client-authentication-method: client_secret_pos
            authorization-grant-type: authorization_code
            redirect-uri: http://${VM_IP}/notice/list
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: ${N_CLIENT_ID}
            client-secret: ${N_CLIENT_SECRET}
            client-name: naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://${VM_IP}/notice/list
            scope:
              - name
              - email
              - profile_image


        provider:
          kakao:
            authorization-uri: ${K_AUTH}
            token-uri: ${K_AUTH_TOKEN}
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


          naver:
            authorization-uri: ${N_AUTH}
            token-uri: ${N_AUTH_TOKEN}
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id